# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Drashot
email: ctaymor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of drashot (teachings or interpretations) on assorted Jewish subjects.
  All work, unless cited to someone else, is copyrighted by Caroline Taymor. You are free to
  excerpt, quote, or paraphrase with attribution for the sake of teaching Torah.

  "And some say Torah studied in order to teach is a Torah of chesed, whereas
  Torah not studied in order to teach is not a Torah of chesed."
  - Sukkah 49b
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: carolinetaymor
# github_username:  ctaymor

# Build settings
markdown: kramdown
